### ISSUE TITLE
Switch from shortcode to TinyMCE button

### ISSUE THREAD

**Issue by tyrann0us** [nabtron/clearboth#3]
Great plugin!
What do you think about switching from a shortcode to a [TinyMCE button](https://codex.wordpress.org/TinyMCE_Custom_Buttons)?

This would have multiple advantages:
* content stays clean after plugin deactivation
* clearing is done directly in the editor visible to the author

It would be great if you could consider this!
Thanks.

**Comment by tyrann0us** [comment]
Nevermind, there's already a [plugin](https://wordpress.org/plugins/tinymce-clear-buttons/) for this.

**Comment by nabtron** [comment]
Thanks for the input, added it as a feature for future release.
